### ISSUE TITLE
Texture is not assigned after upload

### ISSUE THREAD

**Issue by tobiasbrchdt** [NiraOfficial/niraclient#1]
Hello Everyone

We are using the Nira client to upload images, texture images, .mtl and .obj files to the Nira cloud. 
Unfortunately it seems like the texture doesn’t get assigned when we upload all of our files. We can see the model in the viewer, but it’s grey/white.
The command we use is this: 
python nira_upload/niraclient/nira.py asset create <project_id> photogrammetry --dccname "realitycapture" --wait-for-asset-processing 1000 < /app/nira_upload/niraclient/asset_files_list.json 	

As files list we provide the following to the upload:
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0046.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0027.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0005.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0068.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0009.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0062.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/10/24/HYPERLAPSE_0066.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_0000001.obj", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_cameras.csv", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_u1_v1_diffuse.png", "type": "image"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_0000001.mtl", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_0000000.obj", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_0000002.obj", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_0000002.mtl", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-10-24-11-36_6152_nira_0000000.mtl", "type": "extra“}

Do you know whether we have some misconfiguration or what went wrong during the upload? 
When I assign the texture manually in the viewer it seems to work. 

Thank you very much.

**Comment by AndrewJDR** [comment]
Hello,

Please be sure to use `"type": "material"` for your mtl files and `"type": "scene"` for your obj files.
Currently, you're using `"type": "extra"` for these files, which will cause issues.

**Comment by tobiasbrchdt** [comment]
Unfortunately the texture is still not assigned. 
That's what we send now: 
...
{"path": "/mnt/data_dir/photos/2024/12/16/729844830.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/12/16/1607649167.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/12/16/3731206066.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/12/16/2106249908.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/12/16/3910665564.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/photos/2024/12/16/1402217035.JPG", "type": "photogrammetry_image"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000008.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000009.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000001.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000005.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000011.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000003.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000007.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000000.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000002.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000003.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_cameras.csv", "type": "extra"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000007.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000001.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000008.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000006.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000002.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000009.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000010.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000000.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000011.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000010.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000004.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_u1_v1_diffuse.png", "type": "image"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000004.mtl", "type": "material"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000005.obj", "type": "scene"},
{"path": "/mnt/data_dir/models/2024-12-16-19-02_6221_nira_0000006.mtl", "type": "material"}
]


That's the response of the object: {"id":44752,"name":"6221","uuid":"ebb96c19-6727-4be6-97ff-360573791978","curversion":1,"curversionId":44952,"curvpnum":0,"tags":[],"isSequence":false,"isPublic":true,"userMetadata":null,"type":"photogrammetry","dccname":null,"createdBy":-2,"createdAt":"2024-12-18T13:13:24.363Z","updatedAt":"2024-12-18T13:13:27.931Z","initialViewStateId":null,"hideBranding":false,"allowPublic":true,"allowPublicEdits":true,"usesvt":true,"coordsys":null,"coordsysTransform":null,"tier":null,"showInGallery":false,"previewsRemaining":10,"paymentId":null,"passwordRequired":null,"thumbnailAssetId":null,"latitude":null,"longitude":null,"altitude":null,"legacyTier":null} 


When I open the viewer than assign the material manually it's displayed. But we would need this to happen automatically. 
Is there something we forgot or misconfigured? Can it be the order in which the files are uploaded? Any help is appreciated.

**Comment by AndrewJDR** [comment]
@tobiasbrchdt The mtllib line is incorrect inside of your obj file. You have this in your .obj file:
```
mtllib 6221_nira_0000000.mtl
```

But the filename that you uploaded is actually `2024-10-29-14-25_6157_nira_0000000.mtl`. The mtllib line needs to match the filename.

**Comment by tobiasbrchdt** [comment]
Thank you very much! It solved the problem
